### ISSUE TITLE
Edit comment option

### ISSUE THREAD

**Issue by unicornlox** [shawon922/django-blog#1]
Hello shawon;
This app has no option to edit comments.Can you write this function?

**Comment by shawon922** [comment]
Hi,
Thanks for your valuable comment. I will do that as soon as possible.

**Comment by shawon922** [comment]
Hello @trDjango , I have written the function you requested. Please check that. Thank you.

**Comment by unicornlox** [comment]
hello again shawon;
Firstly i thank you shawon. It was great, just like I wanted.You wrote the codes very cleverly.

**Comment by shawon922** [comment]
Thank you very much. If you've any feedback, please let me know.
